---

# Setup mongodb

- name: Register mongodb APT KEY
  apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10

- name: Register mongodb APT REPO
  apt_repository: repo="deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse" state=present

- name: Install Mongodb
  apt: name=mongodb-org update_cache=yes state=latest

- name: Ensure data directory exists
  file: path=/data state=directory owner=mongodb

- name: Configure Mongodb
  template: src=mongod.conf dest=/etc/mongod.conf

- name: Ensure mongod service is enablede
  service: name=mongod enabled=yes state=started

- name: Restart mongod
  service: name=mongod state=restarted
